baseURL = "https://quus.github.io/the-marianq-family-herald"
languageCode = "ko-kr"
title = "My Blog"
theme = "newsroom"

# 한국어 설정
defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = false

# 빌드 설정
buildDrafts = false
buildFuture = false
buildExpired = false

# 페이지네이션
[pagination]
  pagerSize = 10

# 마크다운 설정
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 4

# 사이트 파라미터
[params]
  author = "Your Name"
  description = "내 블로그 설명"
  keywords = ["블로그", "Hugo", "개발"]
  
  # 소셜 미디어
  twitter = "your_twitter"
  github = "your_github"
  email = "your@email.com"
  
  # 뉴스룸 테마 특정 설정
  brand = "My Blog"
  dateFormat = "2006년 1월 2일"
  
  # 댓글 시스템 (선택사항)
  # disqusShortname = "your-disqus-shortname"
  
  # Google Analytics (선택사항)
  # googleAnalytics = "G-XXXXXXXXXX"

# 메뉴 구성
[menu]
  [[menu.main]]
    identifier = "home"
    name = "홈"
    url = "/"
    weight = 1
    
  [[menu.main]]
    identifier = "posts"
    name = "포스트"
    url = "/posts/"
    weight = 2
    
  [[menu.main]]
    identifier = "categories"
    name = "카테고리"
    url = "/categories/"
    weight = 3
    
  [[menu.main]]
    identifier = "tags"
    name = "태그"
    url = "/tags/"
    weight = 4
    
  [[menu.main]]
    identifier = "about"
    name = "소개"
    url = "/about/"
    weight = 5

# 분류법 설정
[taxonomies]
  category = "categories"
  tag = "tags"

# 출력 형식
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

# RSS 설정
[rss]
  limit = 20